# Generated by Django 4.0.1 on 2022-01-18 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Temperature_Fahrenheit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Relative_Humidity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='report_data',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.report')),
            ],
            bases=('dashboard.report',),
        ),
    ]
