# Generated by Django 4.0.1 on 2022-01-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='timestamp',
            field=models.CharField(max_length=200),
        ),
    ]
