# Generated by Django 4.0.1 on 2022-01-19 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_report_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='report_data',
        ),
    ]
